### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by Saloed** [koma-4/SecondCmdLine#1]
1. В Files уже есть метод, который полностью вычитывает файл. [link](https://github.com/koma-4/SecondCmdLine/blob/cc870547d74ed250b76440ef05567909cff5d73d/src/test/java/EncryptorTest.java#L14)
2. А откуда такие ограничения на формат ключа? [link](https://github.com/koma-4/SecondCmdLine/blob/cc870547d74ed250b76440ef05567909cff5d73d/src/main/java/EncryptorLauncher.java#L31)
3. Обычно это шифрование работает не так. У вас сейчас всегда выполняется xor с первым байтом ключа. Обычно же, в ключе несколько байт и xor выполняется по очереди с каждым байтом ключа.
[link](https://github.com/koma-4/SecondCmdLine/blob/cc870547d74ed250b76440ef05567909cff5d73d/src/main/java/Encryptor.java#L21)

**Comment by koma-4** [comment]
1 и 3 поправила. 
А 2ой пункт не совсем поняла. В задании же сказано, что ключ задан в 16ричной системе. Мне не стоит использовать представление ключа в виде 16ричной константы? Исправить на обычное представление 16ричного числа?

**Comment by Saloed** [comment]
Да, действительно, в задании сказано про ключ в шестнадцатеричной системе. Я это как-то не заметил, поскольку обычно, ключ шифрования это обычный текст. 
Тут тогда на ваше усмотрение. Можно и так оставить.

**Comment by koma-4** [comment]
Тогда можно закрыть issues?

**Comment by Saloed** [comment]
Нет ещё нельзя. Я просто сейчас не так часто смотрю, поэтому новых замечаний долго не было. Но вот и они:

1. Длина ключа ни чем не ограничена, так что в `Integer` он может не влезть. Следовательно, `Integer.decode` использовать не хорошо.  [link](https://github.com/koma-4/SecondCmdLine/blob/a6c49da3ad4f333098e48eb764d5c829dca8d174/src/main/java/Encryptor.java#L19)
2. Тут на самом деле не всё так просто. Если заглянуть в [документацию](https://docs.oracle.com/javase/7/docs/api/java/io/Reader.html#read()) к методу `read`, то можно заметить, что прочитанный символ это не всегда 1 байт. Хотелось бы, либо иметь гарантию, что там 1 байт, либо чтобы вариант с двумя байтами тоже обрабатывался. Проще сделать так, чтобы там всегда был 1 байт.  [link](https://github.com/koma-4/SecondCmdLine/blob/a6c49da3ad4f333098e48eb764d5c829dca8d174/src/main/java/Encryptor.java#L23)
3. Лучше сделать 2 метода, `encrypt` и `decrypt`, даже если они оба будут просто вызывать один и тот же метод. Из-за того, что метод один, логика работы шифрования выползает за пределы объекта, в рамках которого должна существовать. Сейчас во всех местах, где происходит дешифрация, вызывается метод `encrypt`, что во-первых сразу вызывает подозрения и приходится идти в код и смотреть там, что из-за особенностей алгоритма это одно и то же, а во-вторых, это  сильно ограничивает возможности изменения логики работы вашего шифрования.   [link](https://github.com/koma-4/SecondCmdLine/blob/a6c49da3ad4f333098e48eb764d5c829dca8d174/src/main/java/Encryptor.java#L31)
4. Кажется, это можно сделать `private`. [link](https://github.com/koma-4/SecondCmdLine/blob/a6c49da3ad4f333098e48eb764d5c829dca8d174/src/main/java/Encryptor.java#L15)
5. Вот такого быть не должно. 
![image](https://user-images.githubusercontent.com/8640896/112634396-977a5400-8e4b-11eb-84ab-aeb8c7b2ccf2.png)

**Comment by koma-4** [comment]
Посмотрите, пожалуйста, как будет время

**Comment by Saloed** [comment]
1. Для таких целей лучше использовать тип `boolean`. Имя переменной `k` для такого флажка туже не очень хорошее. [link](https://github.com/koma-4/SecondCmdLine/blob/fb75a86bd055f08b278b9aade79d878a24d5b0b9/src/main/java/Encryptor.java#L22)
2. Лучше не дублировать проверки для обеих переменных, при учёте того, что вы потом их всё равно кладёте в `key`. [link](https://github.com/koma-4/SecondCmdLine/blob/fb75a86bd055f08b278b9aade79d878a24d5b0b9/src/main/java/EncryptorLauncher.java#L30)
3. Лучше снаружи не пользоваться тем, что `encrypt` и `decrypt` работают одинаково, и вызывать `decrypt`, когда это нужно. [link](https://github.com/koma-4/SecondCmdLine/blob/fb75a86bd055f08b278b9aade79d878a24d5b0b9/src/main/java/EncryptorLauncher.java#L48)

Про число байт в символе. На самом деле, это определяется [кодировкой](https://ru.wikipedia.org/wiki/Набор_символов).
У вас, скорее всего, по умолчанию используется `windows-1251` или `utf-8`, в которых 1 символ это 1 байт. Но есть и другие кодировки, например, `utf-16`, где 1 символ это 2 байта. Поскольку вы явно не указываете кодировку, при чтении и записи используется кодировка по умолчанию. 

В случае, когда по умолчанию у jvm  будет задана, например, `utf-16`, у вас всё начнет ломаться. 
Смотрите, вы считали 1 символ -- 2 байта, разбили его на 2 части по 1 байту. Здесь всё пока хорошо. 
Потом вы делаете `write`, который записывает символ, и делаете вы его 2 раза, для обеих частей исходного символа. 
Поскольку `write` записывает символ, а не байт, он запишет по 2 байта для каждой из частей. В результате, получится, то вы прочитали 2 байта, а записали 4. Ну и дальше всё поломается. 
[link](https://github.com/koma-4/SecondCmdLine/blob/fb75a86bd055f08b278b9aade79d878a24d5b0b9/src/main/java/Encryptor.java#L30)

**Comment by koma-4** [comment]
Поправила. Но не уверенна насчёт того, правильно ли я вас поняла касаемо кодировки

**Comment by Saloed** [comment]
1. А как [эти](https://github.com/koma-4/SecondCmdLine/blob/92b5d609fc4d2fdc20d0a5e7a45267faf1cc3cc8/src/main/java/EncryptorLauncher.java#L29) проверки должны работать, если они происходят до [парсинга аргументов](https://github.com/koma-4/SecondCmdLine/blob/92b5d609fc4d2fdc20d0a5e7a45267faf1cc3cc8/src/main/java/EncryptorLauncher.java#L42)?
2. Лучше придумать какое-то более осмысленное название. Часто в таких случаях делают вообще иначе. Заводят не логическую переменную, а `enum`. Так код более читаемый получается. [link](https://github.com/koma-4/SecondCmdLine/blob/92b5d609fc4d2fdc20d0a5e7a45267faf1cc3cc8/src/main/java/EncryptorLauncher.java#L28)
3. По поводу кодировки да, вы всё поняли правильно. Для описанной проблемы было 2 решения: задать конкретную кодировку явно в коде, или же просто работать с байтами и вообще ни как не сталкиваться с этой проблемой.
4. Лучше не вычитывать все байты сразу, а считывать и обрабатывать по их по одному. Так вы сможете сделать алгоритм работоспособным и для больших файлов. [link](https://github.com/koma-4/SecondCmdLine/blob/92b5d609fc4d2fdc20d0a5e7a45267faf1cc3cc8/src/main/java/Encryptor.java#L23)
5. А зачем возвращать этот временный массив? [link](https://github.com/koma-4/SecondCmdLine/blob/92b5d609fc4d2fdc20d0a5e7a45267faf1cc3cc8/src/main/java/Encryptor.java#L29)

**Comment by koma-4** [comment]
enum это очень интересно. Я правильно поняла, как его можно использовать?

**Comment by Saloed** [comment]
Не совсем. Там можно проще. 

Вам не нужно ничего хранить в значениях енама. Достаточно просто объявить 2 значения и потом просто сравниваться с ними. 

Кстати, имена значений енама принято писать большими буквами (капсом).

**Comment by koma-4** [comment]
Так лучше?`enum Check {ENCRYPT, DECRYPT}`

**Comment by Saloed** [comment]
Да, так лучше

**Comment by Saloed** [comment]
Есть способ сделать это так, чтобы не приходилось исключение ловить. У потока байтов есть способ узнать, есть в нём ещё байты, которые можно прочитать, или уже нет. [link](https://github.com/koma-4/SecondCmdLine/blob/23a177af60ff1986c150d4297c478f507c04749a/src/main/java/Encryptor.java#L28)

**Comment by koma-4** [comment]
Таким способом? `if (input.available() > 0)`

**Comment by Saloed** [comment]
Да. Только лучше эту проверку поместить в условие while, а sym вообще внести в тело цикла. Так получится избежать проблем в случае пустого стрима. Ну и код получится лучше.

**Comment by koma-4** [comment]
Код, и вправду, выглядит приятнее
